# This file was generated by GoReleaser. DO NOT EDIT.
cask "dntls" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "aeeb92973aa3ecd19bdea4a0298d995e30a0f4b17fada51fcbec56e4d1f80e37"
      url "https://github.com/Sakura-Industries-LLC/dntls-testnet/releases/download/cli/v#{version}/dntls_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "498efcd635a863070e341eb2eeef43e3476fae30fccc6fc312f50a0a43170cff"
      url "https://github.com/Sakura-Industries-LLC/dntls-testnet/releases/download/cli/v#{version}/dntls_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2666bf2ca9cfaec47b3527ac3be0bb9d3006f74da7c8256b42af6c2d0851aef4"
      url "https://github.com/Sakura-Industries-LLC/dntls-testnet/releases/download/cli/v#{version}/dntls_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "235372ead85b771fd17c423ec7debfb11313338b94e9e9a645d49ac8bdc2aad4"
      url "https://github.com/Sakura-Industries-LLC/dntls-testnet/releases/download/cli/v#{version}/dntls_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dntls"
  desc "Public command-line client for DNTLS"
  homepage "https://github.com/Sakura-Industries-LLC/dntls-testnet"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dntls"

  # No zap stanza required
end
