# This file was generated by GoReleaser. DO NOT EDIT.
cask "dntls" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "30048617a365b7bab56b6a16f642641c4245ff4aae197f2250f018bdb1027f44"
      url "https://github.com/Sakura-Industries-LLC/dntls-public/releases/download/v#{version}/dntls_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9e3ca36f48fe73f8b5d4ef70b8c1ded2ae6894ddfa9533e89238740b307d7d07"
      url "https://github.com/Sakura-Industries-LLC/dntls-public/releases/download/v#{version}/dntls_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "eb3f2f63a6801135e3b9745b570898933cc93edeb1078202c368c9df8dfbca07"
      url "https://github.com/Sakura-Industries-LLC/dntls-public/releases/download/v#{version}/dntls_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "434e324d3ef4ed4490913371b5f83c932e442d910563a6ef3e21ff4043999dec"
      url "https://github.com/Sakura-Industries-LLC/dntls-public/releases/download/v#{version}/dntls_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dntls"
  desc "Public command-line client for DNTLS"
  homepage "https://github.com/Sakura-Industries-LLC/dntls-public"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dntls"

  # No zap stanza required
end
