# This file was generated by GoReleaser. DO NOT EDIT.
cask "dntls" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "b9e00dab037a31ff851c1edaa6570c0fa5f3a30ca69c3ca8eedecb293271536c"
      url "https://github.com/Sakura-Industries-LLC/dntls-public/releases/download/v#{version}/dntls_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "454db26c3c4653198e00b1eabb4e5be48a1c57ce2ee9fcd47a887160a9a941f0"
      url "https://github.com/Sakura-Industries-LLC/dntls-public/releases/download/v#{version}/dntls_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "447221584df6c30474f4b4c549ef9f6cc0e5a9139037b36d4bac072189d8a9db"
      url "https://github.com/Sakura-Industries-LLC/dntls-public/releases/download/v#{version}/dntls_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "02c1b3f99eb595787f6b18b282604923866a0f4d7030ddf36152f8b2dbca0db5"
      url "https://github.com/Sakura-Industries-LLC/dntls-public/releases/download/v#{version}/dntls_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dntls"
  desc "Public command-line client for DNTLS"
  homepage "https://github.com/Sakura-Industries-LLC/dntls-public"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dntls"

  # No zap stanza required

  caveats <<~EOS
    The current macOS archives are not notarized. If macOS blocks the first
    launch, approve dntls under System Settings > Privacy & Security, then
    run the command again.
  EOS
end
